name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore cv.studio.sln

      - name: Build
        run: dotnet build cv.studio.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test cv.studio.sln --configuration Release --no-build
